실습

In [1]:
import numpy as np

In [4]:
np.__version__

'2.2.6'

numpy 객체 생성

In [7]:
# 리스트 -> ndarray
a = [1,2,3,4,5]
arr = np.array(a)
arr

array([1, 2, 3, 4, 5])

In [9]:
# 튜플 -> ndarray
a =(1,2,3,4,5)
arr = np.array(a)
arr

array([1, 2, 3, 4, 5])

In [10]:
arr.size

5

In [11]:
arr.dtype

dtype('int64')

In [12]:
a = [1.0,2,3,4,5]
arr = np.array(a)
arr

array([1., 2., 3., 4., 5.])

# 2차원 데이터 만들기

In [16]:
a2d = [[1,2,3],[3,4,5],[7,8,9]]
a2d

[[1, 2, 3], [3, 4, 5], [7, 8, 9]]

In [17]:
a2d = np.array(a2d)
a2d

array([[1, 2, 3],
       [3, 4, 5],
       [7, 8, 9]])

In [20]:
# 2차원이기 때문에 행의 갯수
len(a2d)

3

In [21]:
# array의 전체 요소의 갯수 
a2d.size

9

In [22]:
a2d.dtype

dtype('int64')

In [23]:
a2d.shape

(3, 3)

## numpy 객체 저장 & 로딩

In [25]:
np.save('my_array', a2d)

In [26]:
a2d = np.load('my_array.npy')
a2d

array([[1, 2, 3],
       [3, 4, 5],
       [7, 8, 9]])

## BUILT-IN METHODS AND FUNCTIONS (numpy 내장함수)

In [28]:
np.zeros(4)

array([0., 0., 0., 0.])

In [30]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [31]:
np.ones((7,))

array([1., 1., 1., 1., 1., 1., 1.])

In [32]:
np.ones((4,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

## 특정 값으로, 행렬 만들기

In [33]:
np.full((7,),5)

array([5, 5, 5, 5, 5, 5, 5])

In [34]:
np.full((7,2),5)

array([[5, 5],
       [5, 5],
       [5, 5],
       [5, 5],
       [5, 5],
       [5, 5],
       [5, 5]])

In [35]:
np.full((4,2,3),5)

array([[[5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5]]])

## 정수의 배열을 얻고자 할 떄

In [36]:
[0,1,2,3,4,5,6,7,8,9]
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [37]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.arange(5, 30+1)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30])

In [40]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

## 정수 말고 실수를 얻고자 할 때

In [41]:
np.linspace(0,20,15)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        , 11.42857143, 12.85714286,
       14.28571429, 15.71428571, 17.14285714, 18.57142857, 20.        ])

In [42]:
 # reshape

In [43]:
arr = np.arange(1,21+1)

In [44]:
arr2d = arr.reshape(3,7)
arr2d

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

In [45]:
arr2d.shape

(3, 7)

In [47]:
arr2d = arr.reshape(7,3)
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [49]:
arr1d = arr2d.reshape(21)
arr1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21])

In [51]:
arr2d = arr1d.reshape(-1,3)
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [52]:
arr2d.sum()

np.int64(231)

## 여러 단계를 거치치 않고, 한 번에 원하는 다차원 배열로 만들기

In [55]:
a = np.arange(5,20)
a.size

15

In [56]:
a.reshape(3,5)

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [57]:
np.arange(5, 20).reshape(3, 5)

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## 랜덤값으로 채워진 배열 만들기

In [60]:
import random

In [63]:
random.random()

0.6531961683577169

In [64]:
np.random.random(5)

array([0.44656603, 0.33034411, 0.06894749, 0.08306063, 0.18216488])

In [65]:
np.random.random((5,))

array([0.77796715, 0.74641934, 0.07533344, 0.51414593, 0.78694093])

In [66]:
np.random.random((3,5))

array([[0.13533811, 0.43530216, 0.76665569, 0.73685707, 0.74063116],
       [0.00964684, 0.61201338, 0.84314021, 0.65910916, 0.05348353],
       [0.7465511 , 0.58025713, 0.95849711, 0.85030022, 0.30284437]])

In [107]:
random.seed(4)
random.random()

0.23604808973743452

In [115]:
np.random.seed(3)
np.random.random((3,5))

array([[0.5507979 , 0.70814782, 0.29090474, 0.51082761, 0.89294695],
       [0.89629309, 0.12558531, 0.20724288, 0.0514672 , 0.44080984],
       [0.02987621, 0.45683322, 0.64914405, 0.27848728, 0.6762549 ]])

In [116]:
np.random.random((3,5))

array([[0.59086282, 0.02398188, 0.55885409, 0.25925245, 0.4151012 ],
       [0.28352508, 0.69313792, 0.44045372, 0.15686774, 0.54464902],
       [0.78031476, 0.30636353, 0.22195788, 0.38797126, 0.93638365]])

In [75]:
np.random.random((3,5))

array([[0.59086282, 0.02398188, 0.55885409, 0.25925245, 0.4151012 ],
       [0.28352508, 0.69313792, 0.44045372, 0.15686774, 0.54464902],
       [0.78031476, 0.30636353, 0.22195788, 0.38797126, 0.93638365]])

In [76]:
np.random.random((3,5))

array([[0.97599542, 0.67238368, 0.90283411, 0.84575087, 0.37799404],
       [0.09221701, 0.6534109 , 0.55784076, 0.36156476, 0.2250545 ],
       [0.40651992, 0.46894025, 0.26923558, 0.29179277, 0.4576864 ]])

## 시작값과 끝값 주기

In [77]:
np.random.seed(9)

In [78]:
np.random.randint(1,45,(7,))

array([29, 23,  2, 23, 41, 28, 34], dtype=int32)

In [79]:
np.random.randint(1, 45,(3,4))

array([[30, 29,  1, 25],
       [11, 30, 43, 13],
       [19, 23,  2, 36]], dtype=int32)

In [81]:
X = np.random.randint(1, 200,(3,4))