arr의 각 행(row)에서 최댓값만 추출하여
1차원 배열 형태로 출력하시오.

In [1]:
import numpy as np

np.random.seed(11)
arr = np.random.random((4, 5))

In [2]:
arr

array([[0.18026969, 0.01947524, 0.46321853, 0.72493393, 0.4202036 ],
       [0.4854271 , 0.01278081, 0.48737161, 0.94180665, 0.85079509],
       [0.72996447, 0.10873607, 0.89390417, 0.85715425, 0.16508662],
       [0.63233401, 0.02048361, 0.11673727, 0.31636731, 0.15791231]])

In [11]:
max = arr.max(axis = 1)
max

array([0.72493393, 0.94180665, 0.89390417, 0.63233401])

In [ ]:
# slicing 문제 : 다음의 데이터를 추철하는 하는 코드를 작성하시오.
datas = [[40, 20, 75, 42, 11],
       [30, 39, 92, 21, 45],
       [94, 40, 15, 27, 82]]

arr = np.array(datas)
arr
---------------------
# 출력 결과: 
array([11, 45, 82])

In [14]:
datas = [[40, 20, 75, 42, 11],
       [30, 39, 92, 21, 45],
       [94, 40, 15, 27, 82]]

arr = np.array(datas)
arr

array([[40, 20, 75, 42, 11],
       [30, 39, 92, 21, 45],
       [94, 40, 15, 27, 82]])

In [21]:
arr[:, -1]

array([11, 45, 82])

In [ ]:
# numpy함수를 이용하여 10이하의 짝수와 홀수 각각의 리스트를 생성하고,
# 이 두가지 리스트를 사용하여 2차원의 데이터를 만들어라.

---------------------
# 출력 결과: 
array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [41]:
arr = np.arange(1,11)
even = arr[arr % 2 ==0]
odd = arr[arr % 2 ==1]
print(even)
print(odd)

[ 2  4  6  8 10]
[1 3 5 7 9]


In [43]:
res = np.array([even, odd])
res

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

<!-- 10부터 30까지 정수로 이루어진 1차원배열을 만든다음 2차원  (7, -1) 형태로 변환하시오.

그리고 최댓값과 최솟값을 구하시오.

출력결과 :
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]]

max: 30
min: 10 -->

In [49]:
num = np.arange(10,30+1)
num

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30])

In [50]:
num.reshape(7,-1)

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30]])

In [51]:
num.max()

np.int64(30)

In [52]:
num.min()

np.int64(10)

In [55]:
result = (f"max = {num.max()}, min = {num.min()}")

In [56]:
result

'max = 30, min = 10'

In [58]:
num = np.arange(10,30+1)
num
num.reshape(7,-1)
result = (f"max = {num.max()}, min = {num.min()}")
result

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30])

<!-- 문제: 아래 배열을 3행 4열 형태로 reshape 하시오. 변환된 배열에서 마지막 행만 출력하시오. 
datas = [[10, 20, 30, 40, 50, 60],
         [70, 80, 90, 100, 110, 120]] -->

In [61]:
datas = [[10, 20, 30, 40, 50, 60],
         [70, 80, 90, 100, 110, 120]]

datas

[[10, 20, 30, 40, 50, 60], [70, 80, 90, 100, 110, 120]]

In [63]:
arrd = np.reshape(3,4)
arrd

ValueError: cannot reshape array of size 1 into shape (4,)

In [65]:
import numpy as np

datas = [[10, 20, 30, 40, 50, 60],
         [70, 80, 90, 100, 110, 120]]

arr = np.array(datas)      
arr = arr.reshape(3, 4)        

print(arr[-1])   

[ 90 100 110 120]


In [66]:
import random

random.seed(12)

random.random()   
random.random()  
print(random.random())

0.6664104711248381
